### ISSUE TITLE
Error when trying to collect data

### ISSUE THREAD

**Issue by ShalamovRoman** [carla-simulator/data-collector#7]
Hi! I'm trying to collect data using CARLA 0.8.4 and tutorial from readme, but collector raises exception.

Here are my logs
```
Traceback (most recent call last):
File "collect.py", line 483, in <module>
main()
File "collect.py", line 472, in main
collect(client, args)
File "collect.py", line 231, in collect
settings_module, args.debug)
File "collect.py", line 171, in reset_episode
player_target_transform, planner)
File "collect.py", line 141, in calculate_timeout
end_point.orientation.x, end_point.orientation.y, end_point.orientation.z])
File "/home/sergey/Projects/data-collector/carla/planner/planner.py", line 113, in get_shortest_path_distance
track_target, target_ori)
File "/home/sergey/Projects/data-collector/carla/planner/city_track.py", line 99, in compute_route
np.set_printoptions(edgeitems=3, infstr='inf', threshold=np.nan, linewidth=129)
File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 246, in set_printoptions
floatmode, legacy)
File "/usr/lib/python3.7/site-packages/numpy/core/arrayprint.py", line 93, in _make_options_dict
raise ValueError("threshold must be numeric and non-NAN, try "
ValueError: threshold must be numeric and non-NAN, try sys.maxsize for untruncated representation
```
Can somebody explain what parameter I should specify instead of "threshold"?

**Comment by hofbi** [comment]
I faced the same issue running the data collector. I could get it working by changing `threshold=np.nan` to `threshold=0` in your File "/home/sergey/Projects/data-collector/carla/planner/city_track.py", line 99, in compute_route np.set_printoptions(edgeitems=3, infstr='inf', threshold=np.nan, linewidth=129)

With this change I was at least able to run the data collector, but I didn't check in detail if another non-zero value would fit better.
